cars:
  ford:
    ingester:
      runCron: '0/15 * * * * ?' #triggered every 15 secs

spring:
  datasource:
    url: jdbc:h2:mem:carsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
     ddl-auto: create-drop
  h2:
    console:
        enabled: true
        path: /h2
        settings:
          trace: true
