cars:
  ford:
    ingester:
      runCron: 0 * * ? * *


input:
  file:
    ford:
      xml:  ford-example.xml
      xsd:  ford-example.xsd
      brandName: Ford

server:
  origin: http://domain1.com, http://domain2.com

thread:
  cant: 1
  name: mooveitCars

spring:
  datasource:
    url: jdbc:h2:mem:carsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
  h2.console.enabled: true
